apiVersion: v1
kind: Service
metadata:
  name: leapyear-api
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: leapyear-api
    deploymentconfig: leapyear-api
  sessionAffinity: None
  type: ClusterIP
