apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: os-sample-flask-leapyear
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: os-sample-flask-leapyear
    weight: 100
  wildcardPolicy: None
